name: CI

on:
  push:
    paths-ignore:
      - "**/*.md"
      - "**/*.txt"
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  payload-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SDK
        uses: actions/checkout@v4
        with:
          repository: ps5-payload-dev/sdk
          path: sdk

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install build-essential clang-18 lld-18 xxd yasm nasm

      - name: Install SDK
        working-directory: sdk
        run: |
          make DESTDIR=/opt/ps5-payload-sdk install

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Payload
        run: |
          export PS5_PAYLOAD_SDK=/opt/ps5-payload-sdk
          make dist

      # upload files separately, with archive: false, so that github shows the sha hashes directly
      - name: Upload Payload ELF
        uses: actions/upload-artifact@v7
        with:
          path: ./ps5-self-pager-system-common-lib.elf
          if-no-files-found: error
          archive: false

      - name: Upload Payload ELF
        uses: actions/upload-artifact@v7
        with:
          path: ./ps5-self-pager-full-system.elf
          if-no-files-found: error
          archive: false

      - name: Upload Payload ELF
        uses: actions/upload-artifact@v7
        with:
          path: ./ps5-self-pager-shellcore.elf
          if-no-files-found: error
          archive: false

      - name: Upload Payload ELF
        uses: actions/upload-artifact@v7
        with:
          path: ./ps5-self-pager-game.elf
          if-no-files-found: error
          archive: false
